### ISSUE TITLE
在Front-matter中加入categories就会出现，注释掉就不会报错。

### ISSUE THREAD

**Issue by Harker668** [ch1ny/kira-hexo#20]
ERROR
TypeError: E:\hexo\blog\node_modules\hexo-theme-kira\layout\post.ejs:40
    38|         <div class="kira-post-nav">
    39|                 <nav class="post-nav">
 >> 40|                         <% site.categories.map(function(category){ %> <%
    41|                         page.categories.map(function(page_category){ %> <% if(page_category.name ==
    42|                         category.name){ %>
    43|                         

Cannot read properties of undefined (reading 'map')
    at eval ("E:\\hexo\\blog\\node_modules\\hexo-theme-kira\\layout\\post.ejs":69:20)
    at _Query.map (E:\hexo\blog\node_modules\warehouse\lib\query.js:213:19)
    at eval ("E:\\hexo\\blog\\node_modules\\hexo-theme-kira\\layout\\post.ejs":66:24)
    at post (E:\hexo\blog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (E:\hexo\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\hexo\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\hexo\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\hexo\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\hexo\blog\node_modules\hexo\lib\hexo\router.js:47:5)

**Comment by ch1ny** [comment]
可以看看 Issue #10 ，问题应该是类似的。
麻烦检查一下文章是否归置在了 `_post` 文件夹下。

**Comment by ch1ny** [comment]
您好，如果没有其他问题的话我就先将 issue 关闭了。后续还存在问题的话您可以重新开启该 issue 。
