### ISSUE TITLE
安装上后的问题

### ISSUE THREAD

**Issue by adolphshi** [ch1ny/kira-hexo#42]
每一次打开post都会变成一片空白
还会报错如下：

```
Unhandled rejection TypeError: E:\blog\myblog\node_modules\hexo-theme-kira\layou
    87|         <div class="kira-post-footer">
    88|                 <%- partial('components/comments/gitalk') %>
 >> 89|                 <%- partial('components/comments/giscus') %>
    90|         </div>
    91|         <% } %>
    92| </div>

E:\blog\myblog\node_modules\hexo-theme-kira\layout\components\comments\giscus.ej
 >> 1| <% if (theme.giscus.active) { %>
    2|  <div class="giscus"></div>
    3|   <% if (theme.giscus.mapping === 'specific' || theme.giscus.mapping ===
    4|     <script src="<%- theme.cdn.giscus.js %>"

Cannot read properties of undefined (reading 'active')
    at eval ("E:\\blog\\myblog\\node_modules\\hexo-theme-kira\\layout\\component
    at giscus (E:\blog\myblog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiledSync (E:\blog\myblog\node_modules\hexo\lib\theme\view.js:1
    at _View.renderSync (E:\blog\myblog\node_modules\hexo\lib\theme\view.js:59:2
    at Object.partial (E:\blog\myblog\node_modules\hexo\lib\plugins\helper\parti
    at eval ("E:\\blog\\myblog\\node_modules\\hexo-theme-kira\\layout\\post.ejs"
    at post (E:\blog\myblog\node_modules\ejs\lib\ejs.js:703:17)
    at _View._compiled (E:\blog\myblog\node_modules\hexo\lib\theme\view.js:136:5
    at _View.render (E:\blog\myblog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\blog\myblog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\blog\myblog\node_modules\bluebird\js\release\util.js:16:23
    at E:\blog\myblog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\blog\myblog\node_modules\hexo\lib\hexo\router.js:47
    at Readable.read (node:internal/streams/readable:715:12)
    at resume_ (node:internal/streams/readable:1222:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:2
```
怎么做

**Comment by adolphshi** [comment]
怎么做

**Comment by ch1ny** [comment]
https://hexo.kira.host/config/config.html
这里在 `_config.kira.yml` 下补充一下 giscus 的配置
```yml
giscus:
    active: false # 是否启用 giscus
```
